<?php
/** Sakht Sar — WordPress bootstrap, CPTs, taxonomies, meta boxes and Customizer. */
if (!defined('ABSPATH')) exit;
require_once get_template_directory() . '/inc/profile-content.php';

define('SAKHTSAR_VERSION', '2.5.0');
function sakhtsar_setup(){add_theme_support('title-tag');add_theme_support('post-thumbnails');add_theme_support('html5',array('search-form','comment-form','comment-list','gallery','caption','style','script'));add_theme_support('custom-logo',array('height'=>80,'width'=>180,'flex-height'=>true,'flex-width'=>true));register_nav_menus(array('primary'=>'منوی اصلی','footer_quick'=>'فوتر — دسترسی سریع','footer_about'=>'فوتر — درباره سخت‌سر'));}
add_action('after_setup_theme','sakhtsar_setup');
function sakhtsar_assets(){wp_enqueue_style('sakhtsar-style',get_stylesheet_uri(),array(),SAKHTSAR_VERSION);wp_enqueue_style('sakhtsar-rtl-overrides',get_template_directory_uri().'/assets/css/rtl-overrides.css',array('sakhtsar-style'),SAKHTSAR_VERSION);wp_enqueue_style('sakhtsar-footer-reference',get_template_directory_uri().'/assets/css/footer-reference.css',array('sakhtsar-style','sakhtsar-rtl-overrides'),SAKHTSAR_VERSION);wp_add_inline_style('sakhtsar-footer-reference',':root{--sakhtsar-social-size:'.max(12,min(64,absint(sakhtsar_get('social_icon_size',24)))).'px;}');if(get_query_var('sakhtsar_profile'))wp_enqueue_style('sakhtsar-profile',get_template_directory_uri().'/assets/css/profile.css',array('sakhtsar-style','sakhtsar-rtl-overrides'),SAKHTSAR_VERSION);wp_enqueue_script('sakhtsar-main',get_template_directory_uri().'/assets/js/main.js',array(),SAKHTSAR_VERSION,true);}
add_action('wp_enqueue_scripts','sakhtsar_assets');
function sakhtsar_register_content(){$types=array('place'=>array('جاهای رامسر','جای رامسر','dashicons-location-alt','places'),'trip'=>array('مسیرهای گردشگری','مسیر گردشگری','dashicons-location','trips'),'event'=>array('رویدادها','رویداد','dashicons-calendar-alt','events'),'magazine'=>array('مجله سخت‌سر','مقاله مجله','dashicons-edit','magazine'),'gallery_item'=>array('گالری','تصویر گالری','dashicons-format-gallery','gallery'));foreach($types as $slug=>$data)register_post_type($slug,array('labels'=>array('name'=>$data[0],'singular_name'=>$data[1],'add_new'=>'افزودن جدید','add_new_item'=>'افزودن '.$data[1],'edit_item'=>'ویرایش '.$data[1],'new_item'=>'جدید','view_item'=>'مشاهده','search_items'=>'جستجو','not_found'=>'موردی پیدا نشد','menu_name'=>$data[0]),'public'=>true,'show_in_rest'=>true,'menu_icon'=>$data[2],'rewrite'=>array('slug'=>$data[3]),'has_archive'=>true,'supports'=>array('title','editor','thumbnail','excerpt','revisions','author')));register_taxonomy('place_type','place',array('labels'=>array('name'=>'دسته‌بندی مکان','singular_name'=>'دسته مکان'),'public'=>true,'show_in_rest'=>true,'hierarchical'=>true,'rewrite'=>array('slug'=>'place-type')));register_taxonomy('trip_type','trip',array('labels'=>array('name'=>'نوع مسیر','singular_name'=>'نوع مسیر'),'public'=>true,'show_in_rest'=>true,'hierarchical'=>true,'rewrite'=>array('slug'=>'trip-type')));register_taxonomy('event_type','event',array('labels'=>array('name'=>'نوع رویداد','singular_name'=>'نوع رویداد'),'public'=>true,'show_in_rest'=>true,'hierarchical'=>true,'rewrite'=>array('slug'=>'event-type')));register_taxonomy('magazine_category','magazine',array('labels'=>array('name'=>'دسته‌بندی مجله','singular_name'=>'دسته مجله'),'public'=>true,'show_in_rest'=>true,'hierarchical'=>true,'rewrite'=>array('slug'=>'magazine-category')));}
add_action('init','sakhtsar_register_content');
function sakhtsar_profile_route(){add_rewrite_rule('^profile/?$','index.php?sakhtsar_profile=1','top');add_rewrite_tag('%sakhtsar_profile%','([01])');} add_action('init','sakhtsar_profile_route',1);
function sakhtsar_profile_template($template){if(get_query_var('sakhtsar_profile')){$profile=get_template_directory().'/profile.php';if(file_exists($profile))return $profile;}return $template;} add_filter('template_include','sakhtsar_profile_template');
function sakhtsar_meta_boxes(){add_meta_box('sakhtsar_place_details','جزئیات مکان','sakhtsar_place_box','place','normal','high');add_meta_box('sakhtsar_trip_details','جزئیات مسیر','sakhtsar_trip_box','trip','normal','high');add_meta_box('sakhtsar_event_details','جزئیات رویداد','sakhtsar_event_box','event','normal','high');add_meta_box('sakhtsar_gallery_details','جزئیات گالری','sakhtsar_gallery_box','gallery_item','normal','high');} add_action('add_meta_boxes','sakhtsar_meta_boxes');
function sakhtsar_meta_input($key,$label,$value,$type='text'){printf('<p><label><strong>%s</strong></label><br><input class="widefat" type="%s" name="%s" value="%s"></p>',esc_html($label),esc_attr($type),esc_attr($key),esc_attr($value));}
function sakhtsar_place_box($post){wp_nonce_field('sakhtsar_meta','sakhtsar_meta_nonce');sakhtsar_meta_input('sakhtsar_address','آدرس',get_post_meta($post->ID,'sakhtsar_address',true));sakhtsar_meta_input('sakhtsar_rating','امتیاز',get_post_meta($post->ID,'sakhtsar_rating',true));sakhtsar_meta_input('sakhtsar_lat','عرض جغرافیایی',get_post_meta($post->ID,'sakhtsar_lat',true));sakhtsar_meta_input('sakhtsar_lng','طول جغرافیایی',get_post_meta($post->ID,'sakhtsar_lng',true));}
function sakhtsar_trip_box($post){wp_nonce_field('sakhtsar_meta','sakhtsar_meta_nonce');sakhtsar_meta_input('sakhtsar_duration','مدت مسیر',get_post_meta($post->ID,'sakhtsar_duration',true));sakhtsar_meta_input('sakhtsar_distance','مسافت',get_post_meta($post->ID,'sakhtsar_distance',true));sakhtsar_meta_input('sakhtsar_stops','تعداد توقف‌ها',get_post_meta($post->ID,'sakhtsar_stops',true));sakhtsar_meta_input('sakhtsar_difficulty','سطح مسیر',get_post_meta($post->ID,'sakhtsar_difficulty',true));}
function sakhtsar_event_box($post){wp_nonce_field('sakhtsar_meta','sakhtsar_meta_nonce');sakhtsar_meta_input('sakhtsar_event_date','تاریخ رویداد',get_post_meta($post->ID,'sakhtsar_event_date',true),'date');sakhtsar_meta_input('sakhtsar_event_time','ساعت',get_post_meta($post->ID,'sakhtsar_event_time',true),'time');sakhtsar_meta_input('sakhtsar_event_location','محل برگزاری',get_post_meta($post->ID,'sakhtsar_event_location',true));}
function sakhtsar_gallery_box($post){wp_nonce_field('sakhtsar_meta','sakhtsar_meta_nonce');sakhtsar_meta_input('sakhtsar_gallery_credit','اعتبار تصویر',get_post_meta($post->ID,'sakhtsar_gallery_credit',true));}
function sakhtsar_save_meta($post_id){if(!isset($_POST['sakhtsar_meta_nonce'])||!wp_verify_nonce(sanitize_text_field(wp_unslash($_POST['sakhtsar_meta_nonce'])),'sakhtsar_meta'))return;if(defined('DOING_AUTOSAVE')&&DOING_AUTOSAVE)return;if(!current_user_can('edit_post',$post_id))return;$keys=array('sakhtsar_address','sakhtsar_rating','sakhtsar_lat','sakhtsar_lng','sakhtsar_duration','sakhtsar_distance','sakhtsar_stops','sakhtsar_difficulty','sakhtsar_event_date','sakhtsar_event_time','sakhtsar_event_location','sakhtsar_gallery_credit');foreach($keys as $key)if(isset($_POST[$key]))update_post_meta($post_id,$key,sanitize_text_field(wp_unslash($_POST[$key])));} add_action('save_post','sakhtsar_save_meta');
function sakhtsar_customize($wp_customize){
$wp_customize->add_section('sakhtsar_site',array('title'=>'سخت‌سر | تنظیمات سایت','description'=>'تنظیمات حرفه‌ای هدر، صفحه اصلی و فوتر','priority'=>25));
$fields=array('hero_title'=>array('عنوان اصلی','رامسر','text','sanitize_text_field'),'hero_subtitle'=>array('زیرعنوان','بهشت همیشه سبز','text','sanitize_text_field'),'hero_kicker'=>array('متن بالای عنوان','سخت سر، راهنمای جامع شما برای کشف طبیعت، فرهنگ و تاریخ','text','sanitize_text_field'),'hero_description'=>array('توضیح Hero','سخت سر، راهنمای جامع گردشگری رامسر','textarea','sanitize_textarea_field'),'weather_temp'=>array('دمای فعلی','18°','text','sanitize_text_field'),'weather_state'=>array('وضعیت هوا','نیمه ابری','text','sanitize_text_field'),'footer_description'=>array('توضیح Footer','سخت‌سر، راهنمای جامع گردشگری، فرهنگ و زندگی رامسر','textarea','sanitize_textarea_field'),'footer_phone'=>array('شماره تماس','011-552xxxxx','text','sanitize_text_field'),'footer_email'=>array('ایمیل','info@sakhtsar.ir','text','sanitize_email'),'footer_address'=>array('آدرس','رامسر، میدان شهرداری','text','sanitize_text_field'));foreach($fields as $id=>$f){$wp_customize->add_setting('sakhtsar_'.$id,array('default'=>$f[1],'sanitize_callback'=>$f[3]));$wp_customize->add_control('sakhtsar_'.$id,array('section'=>'sakhtsar_site','label'=>$f[0],'type'=>$f[2]));}
$wp_customize->add_setting('sakhtsar_hero_image',array('default'=>'','sanitize_callback'=>'esc_url_raw'));$wp_customize->add_control(new WP_Customize_Image_Control($wp_customize,'sakhtsar_hero_image',array('section'=>'sakhtsar_site','label'=>'تصویر اصلی Hero')));
$wp_customize->add_setting('sakhtsar_footer_logo',array('default'=>'','sanitize_callback'=>'esc_url_raw'));$wp_customize->add_control(new WP_Customize_Image_Control($wp_customize,'sakhtsar_footer_logo',array('section'=>'sakhtsar_site','label'=>'لوگوی Footer')));
$socials=array('instagram'=>'اینستاگرام','telegram'=>'تلگرام','youtube'=>'یوتیوب','aparat'=>'آپارات','social5'=>'شبکه اجتماعی پنجم');foreach($socials as $id=>$label){$wp_customize->add_setting('sakhtsar_social_'.$id.'_url',array('default'=>'#','sanitize_callback'=>'esc_url_raw'));$wp_customize->add_control('sakhtsar_social_'.$id.'_url',array('section'=>'sakhtsar_site','label'=>'لینک '.$label,'type'=>'url'));$wp_customize->add_setting('sakhtsar_social_'.$id.'_icon',array('default'=>'','sanitize_callback'=>'esc_url_raw'));$wp_customize->add_control(new WP_Customize_Image_Control($wp_customize,'sakhtsar_social_'.$id.'_icon',array('section'=>'sakhtsar_site','label'=>'آیکون '.$label)));}$wp_customize->add_setting('sakhtsar_social_icon_size',array('default'=>24,'sanitize_callback'=>'absint'));$wp_customize->add_control('sakhtsar_social_icon_size',array('section'=>'sakhtsar_site','label'=>'اندازه آیکون‌های شبکه‌های اجتماعی (px)','type'=>'number','input_attrs'=>array('min'=>12,'max'=>64,'step'=>1)));
$wp_customize->add_section('sakhtsar_profile',array('title'=>'سخت‌سر | پروفایل کاربری','description'=>'تمام تنظیمات ظاهری و متن‌های صفحه پروفایل','priority'=>26));
$profile_fields=array('profile_title'=>array('عنوان بنر','پروفایل کاربری','text','sanitize_text_field'),'profile_breadcrumb'=>array('متن مسیر صفحه','خانه  ‹  پروفایل کاربری','text','sanitize_text_field'),'profile_default_bio'=>array('معرفی پیش‌فرض','سلام! من عاشق سفر، طبیعت و کشف مکان‌های جدید هستم. همیشه سعی می‌کنم بهترین تجربه‌هایم را با دیگران به اشتراک بگذارم.','textarea','sanitize_textarea_field'),'profile_stat_trips'=>array('عنوان آمار مسیرها','مسیرهای سفر','text','sanitize_text_field'),'profile_stat_places'=>array('عنوان آمار مکان‌ها','جاذبه‌ها','text','sanitize_text_field'),'profile_stat_articles'=>array('عنوان آمار مقالات','مقالات','text','sanitize_text_field'),'profile_stat_events'=>array('عنوان آمار ویدیوها','ویدیوها','text','sanitize_text_field'),'profile_about_title'=>array('عنوان درباره من','درباره من','text','sanitize_text_field'),'profile_personal_title'=>array('عنوان اطلاعات شخصی','اطلاعات شخصی','text','sanitize_text_field'),'profile_favorites_title'=>array('عنوان علاقه‌مندی‌ها','علاقه‌مندی‌های من','text','sanitize_text_field'),'profile_history_title'=>array('عنوان تاریخچه','تاریخچه بازدیدها','text','sanitize_text_field'),'profile_comments_title'=>array('عنوان نظرات','آخرین نظرات من','text','sanitize_text_field'),'profile_badges_title'=>array('عنوان نشان‌ها','نشان‌ها و دستاوردها','text','sanitize_text_field'),'profile_trips_title'=>array('عنوان مسیرها','مسیرهای من','text','sanitize_text_field'),'badge_one'=>array('نشان اول','سفرهای زیاد','text','sanitize_text_field'),'badge_two'=>array('نشان دوم','کشف‌گر طبیعت','text','sanitize_text_field'),'badge_three'=>array('نشان سوم','عضو ویژه','text','sanitize_text_field'),'badge_four'=>array('نشان چهارم','نویسنده برتر','text','sanitize_text_field'),'badge_one_desc'=>array('توضیح نشان اول','۱۰ سفر','text','sanitize_text_field'),'badge_two_desc'=>array('توضیح نشان دوم','۲۰ جاذبه','text','sanitize_text_field'),'badge_three_desc'=>array('توضیح نشان سوم','۱ سال','text','sanitize_text_field'),'badge_four_desc'=>array('توضیح نشان چهارم','۵ مقاله','text','sanitize_text_field'));foreach($profile_fields as $id=>$f){$wp_customize->add_setting('sakhtsar_'.$id,array('default'=>$f[1],'sanitize_callback'=>$f[3]));$wp_customize->add_control('sakhtsar_'.$id,array('section'=>'sakhtsar_profile','label'=>$f[0],'type'=>$f[2]));}
$wp_customize->add_setting('sakhtsar_profile_cover_image',array('default'=>'','sanitize_callback'=>'esc_url_raw'));$wp_customize->add_control(new WP_Customize_Image_Control($wp_customize,'sakhtsar_profile_cover_image',array('section'=>'sakhtsar_profile','label'=>'عکس بنر پروفایل')));
$wp_customize->add_setting('sakhtsar_profile_cover_position',array('default'=>'center center','sanitize_callback'=>'sanitize_text_field'));$wp_customize->add_control('sakhtsar_profile_cover_position',array('section'=>'sakhtsar_profile','label'=>'جایگاه عکس بنر','type'=>'text','description'=>'مثلاً center center یا center top'));
}
add_action('customize_register','sakhtsar_customize');
function sakhtsar_profile_user_fields($user){if(!current_user_can('edit_users')&&get_current_user_id()!=$user->ID)return;wp_nonce_field('sakhtsar_user_profile','sakhtsar_user_profile_nonce');?><h2>سخت‌سر — اطلاعات پروفایل</h2><table class="form-table"><tr><th><label for="sakhtsar_phone">شماره موبایل</label></th><td><input class="regular-text" name="sakhtsar_phone" id="sakhtsar_phone" value="<?php echo esc_attr(get_user_meta($user->ID,'sakhtsar_phone',true));?>"></td></tr><tr><th><label for="sakhtsar_location">محل زندگی</label></th><td><input class="regular-text" name="sakhtsar_location" id="sakhtsar_location" value="<?php echo esc_attr(get_user_meta($user->ID,'sakhtsar_location',true));?>"></td></tr><tr><th><label for="sakhtsar_birthdate">تاریخ تولد</label></th><td><input class="regular-text" name="sakhtsar_birthdate" id="sakhtsar_birthdate" value="<?php echo esc_attr(get_user_meta($user->ID,'sakhtsar_birthdate',true));?>" placeholder="مثلاً 1388/01/20"></td></tr><tr><th><label for="sakhtsar_favorite_places">شناسه مکان‌های علاقه‌مندی</label></th><td><input class="regular-text" name="sakhtsar_favorite_places" id="sakhtsar_favorite_places" value="<?php echo esc_attr(get_user_meta($user->ID,'sakhtsar_favorite_places',true));?>"><p class="description">شناسه پست‌ها را با کاما جدا کن؛ مثال: 12,45,78</p></td></tr></table><?php }
add_action('show_user_profile','sakhtsar_profile_user_fields');add_action('edit_user_profile','sakhtsar_profile_user_fields');
function sakhtsar_save_profile_user_fields($user_id){if(!isset($_POST['sakhtsar_user_profile_nonce'])||!wp_verify_nonce(sanitize_text_field(wp_unslash($_POST['sakhtsar_user_profile_nonce'])),'sakhtsar_user_profile'))return;if(!current_user_can('edit_user',$user_id))return;foreach(array('sakhtsar_phone','sakhtsar_location','sakhtsar_birthdate','sakhtsar_favorite_places') as $key)if(isset($_POST[$key]))update_user_meta($user_id,$key,sanitize_text_field(wp_unslash($_POST[$key])));}
add_action('personal_options_update','sakhtsar_save_profile_user_fields');add_action('edit_user_profile_update','sakhtsar_save_profile_user_fields');
function sakhtsar_get($key,$fallback=''){return get_theme_mod('sakhtsar_'.$key,$fallback);} function sakhtsar_img($url){return esc_url($url);} function sakhtsar_featured_image($post_id,$fallback=''){$url=get_the_post_thumbnail_url($post_id,'large');return $url?:$fallback;}
function sakhtsar_footer_socials(){$socials=array('instagram'=>array('اینستاگرام','◎'),'telegram'=>array('تلگرام','➤'),'youtube'=>array('یوتیوب','▶'),'aparat'=>array('آپارات','◈'),'social5'=>array('شبکه اجتماعی','⊕'));foreach($socials as $id=>$data){$url=sakhtsar_get('social_'.$id.'_url','#');$icon=sakhtsar_get('social_'.$id.'_icon','');echo '<a href="'.esc_url($url).'" aria-label="'.esc_attr($data[0]).'" title="'.esc_attr($data[0]).'">';if($icon)echo '<img src="'.esc_url($icon).'" alt="" aria-hidden="true">';else echo '<span>'.esc_html($data[1]).'</span>';echo '</a>';}}
function sakhtsar_flush_rewrites(){if(get_option('sakhtsar_rewrite_version')!=='2.5.0'){flush_rewrite_rules(false);update_option('sakhtsar_rewrite_version','2.5.0');}} add_action('init','sakhtsar_flush_rewrites',99);
