<?php if (!defined('ABSPATH')) exit; ?><!doctype html><html <?php language_attributes(); ?>><head><meta charset="<?php bloginfo('charset'); ?>"><meta name="viewport" content="width=device-width, initial-scale=1"><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Vazirmatn:wght@400;500;600;700;800;900&display=swap"><style>
.site-header{border-radius:0 0 18px 18px;background:rgba(255,255,255,.98);box-shadow:0 4px 18px rgba(7,50,25,.05)}
.header-inner{height:76px;display:flex;align-items:center;gap:28px;direction:rtl}
.brand{order:1;margin-left:auto;gap:10px;min-width:205px;justify-content:flex-start;color:#0b4b27;text-align:right}
.brand strong{font-size:21px;letter-spacing:-.8px;font-weight:900}.brand small{font-size:8px;margin-top:3px;color:#7a827c}.brand-mark{width:58px;height:48px;color:#0b4b27}
.main-nav{order:2;flex:1;justify-content:center;gap:25px;font-size:12px;direction:rtl;white-space:nowrap}
.main-nav a{padding:27px 0 24px;font-weight:800;color:#26302a}.main-nav a:after{height:2px}.main-nav a:hover,.main-nav a.is-active{color:#0b4b27}
.header-tools{order:3;margin-right:auto;gap:8px;direction:ltr;flex:0 0 auto}
.header-tools .icon-btn{width:38px;height:38px;font-size:0}.header-tools .icon-btn svg{width:18px;height:18px;stroke:currentColor;fill:none;stroke-width:1.8;stroke-linecap:round;stroke-linejoin:round}
.weather-pill{height:38px;padding:0 12px;font-size:11px;gap:6px}.weather-pill svg{width:17px;height:17px;stroke:currentColor;fill:none;stroke-width:1.7;stroke-linecap:round;stroke-linejoin:round}
.login-btn{height:38px;padding:0 15px;font-size:11px;white-space:nowrap}
@media(max-width:1120px){.header-inner{gap:18px}.main-nav{gap:16px}.main-nav a{font-size:11px}.brand{min-width:180px}.brand strong{font-size:19px}}
@media(max-width:900px){.header-inner{gap:12px}.main-nav{gap:11px}.main-nav a{font-size:10px}.brand{min-width:155px}.brand-mark{width:48px}.brand strong{font-size:17px}.brand small{font-size:7px}.header-tools{gap:5px}.login-btn{padding:0 10px;font-size:10px}.weather-pill{padding:0 8px}}
@media(max-width:700px){.header-inner{width:calc(100% - 24px);height:auto;min-height:68px;flex-wrap:wrap;padding:9px 0;gap:9px}.brand{order:1;margin-left:auto;min-width:auto}.header-tools{order:2;margin-right:0}.main-nav{order:3;flex-basis:100%;justify-content:flex-start;overflow-x:auto;gap:20px;border-top:1px solid var(--ss-line);padding-top:7px}.main-nav a{padding:5px 0 7px;font-size:10px}.main-nav a:after{bottom:0}.brand-mark{width:42px;height:38px}.brand strong{font-size:17px}.brand small{font-size:6px}.header-tools .icon-btn{width:34px;height:34px}.weather-pill{height:34px}.login-btn{height:34px;padding:0 9px}}
</style><?php wp_head(); ?></head><body <?php body_class(); ?>><?php wp_body_open(); ?><header class="site-header"><div class="container header-inner">
<a class="brand" href="<?php echo esc_url(home_url('/')); ?>" aria-label="<?php echo esc_attr(get_bloginfo('name')); ?>"><span><strong><?php bloginfo('name'); ?></strong><small>سامانه جامع گردشگری رامسر</small></span><svg class="brand-mark" viewBox="0 0 80 70" fill="none" aria-hidden="true"><path d="M5 56 27 30l9 9L56 15l19 23" stroke="currentColor" stroke-width="5" stroke-linecap="round" stroke-linejoin="round"/><path d="m17 57 18-17 11 11 12-13 17 19" stroke="currentColor" stroke-width="4" stroke-linecap="round"/><path d="M46 10c8 5 14 6 23 5" stroke="currentColor" stroke-width="4" stroke-linecap="round"/></svg></a>
<nav class="main-nav" aria-label="منوی اصلی"><?php if (has_nav_menu('primary')) { wp_nav_menu(array('theme_location'=>'primary','container'=>false,'fallback_cb'=>false,'items_wrap'=>'%3$s')); } else { ?><a class="is-active" href="<?php echo esc_url(home_url('/')); ?>">خانه</a><a href="<?php echo esc_url(home_url('/#places')); ?>">مسیرهای دیدنی</a><a href="<?php echo esc_url(home_url('/#events')); ?>">رویدادها</a><a href="<?php echo esc_url(home_url('/#trips')); ?>">گردشگری</a><a href="<?php echo esc_url(home_url('/#trips')); ?>">سفر</a><a href="<?php echo esc_url(home_url('/#magazine')); ?>">مجله</a><a href="<?php echo esc_url(home_url('/#about')); ?>">درباره رامسر</a><a href="<?php echo esc_url(home_url('/#contact')); ?>">تماس با ما</a><?php } ?></nav>
<div class="header-tools"><a class="login-btn" href="<?php echo esc_url(wp_login_url()); ?>"><svg width="15" height="15" viewBox="0 0 24 24" aria-hidden="true"><path d="M15 20v-1.5a3.5 3.5 0 0 0-3.5-3.5h-5A3.5 3.5 0 0 0 3 18.5V20M9 11a4 4 0 1 0 0-8 4 4 0 0 0 0 8Zm7-5v6m-3-3h6" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"/></svg>ورود / ثبت‌نام</a><button class="icon-btn" type="button" aria-label="جستجو" data-search-focus><svg viewBox="0 0 24 24"><circle cx="11" cy="11" r="6.5"/><path d="m16 16 5 5"/></svg></button><button class="icon-btn" type="button" aria-label="علاقه‌مندی‌ها"><svg viewBox="0 0 24 24"><path d="M20.8 8.8c0 5.5-8.8 10.2-8.8 10.2S3.2 14.3 3.2 8.8A4.7 4.7 0 0 1 12 6.1a4.7 4.7 0 0 1 8.8 2.7Z"/></svg></button><span class="weather-pill"><svg viewBox="0 0 24 24"><circle cx="12" cy="12" r="3.5"/><path d="M12 2v2m0 16v2M4.9 4.9l1.4 1.4m11.4 11.4 1.4 1.4M2 12h2m16 0h2M4.9 19.1l1.4-1.4M17.7 6.3l1.4-1.4"/></svg><?php echo esc_html(sakhtsar_get('weather_temp','18°')); ?></span></div></div></header>